# #############################################################################
# Copyright (c) 2023,2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################

name: Database Backup - PostgresSQL

on:
  # push:
  #   branches:
  #     - backup-db

  workflow_dispatch:
      inputs:
        cluster_context:
          description: "Select the AKS environment"
          default: "arena2036-x-fed-services"
          required: true
          type: choice
          options:
            - demo-cluster
            - arena2036-x-edc-cluster
            - arena2036-x-fed-services
        resource_group:
          description: "Select Azure resource group"
          default: "arena2036-x-federated-services"
          required: true
          type: choice
          options:
            - demo
            - arena2036-x-edc
            - arena2036-x-federated-services
        namespace:
          description: "Kubernetes namespace to back up e.g, release24-12"
          required: true
          default: "release24-12"
        release_name:
          description: "Enter release name e.g, fed-services"
          required: true
          default: "fed-services"

  schedule:
    - cron: '0 20 * * 5' # Runs every Friday at 8 PM UTC

jobs:
  db-backup:
    name: Run PostgreSQL Backups
    runs-on: ubuntu-latest

    env:
      TARGET_CONTEXT: ${{ github.event.inputs.cluster_context || 'arena2036-x-fed-services' }}
      RESOURCE_GROUP: ${{ github.event.inputs.resource_group || 'arena2036-x-federated-services' }}
      NAMESPACE: ${{ github.event.inputs.namespace || 'release24-12' }}
      RELEASE_NAME: ${{ github.event.inputs.release_name || 'fed-services' }}
      AZURE_ACCOUNT: "arena2036"
      AZURE_CONTAINER: "database-backup"

      SHAREDIDP_DB_PASSWORD: ${{ secrets.SHAREDIDP_DB_PASSWORD }}
      POSTGRESQL_DB: ${{ secrets.POSTGRESQL_DB }}
      PORTAL_DB_PASSWORD: ${{ secrets.PORTAL_DB_PASSWORD }}
      ISSUER_DB_PASSWORD: ${{ secrets.ISSUER_DB_PASSWORD }}
      DISCOVERYFINDER_DB_PASSWORD: ${{ secrets.DISCOVERYFINDER_DB_PASSWORD }}
      DATACONSUMER_DB_PASSWORD: ${{ secrets.DATACONSUMER_DB_PASSWORD }}
      CENTRALIDP_DB_PASSWORD: ${{ secrets.CENTRALIDP_DB_PASSWORD }}
      BPNDISCOVERY_DB_PASSWORD: ${{ secrets.BPNDISCOVERY_DB_PASSWORD }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Workflow Inputs
        run: |
          echo "Cluster context: ${{ github.event.inputs.cluster_context }}"
          echo "Resource group: ${{ github.event.inputs.resource_group }}"
          echo "Namespace:      ${{ github.event.inputs.namespace }}"
          echo "Release name: ${{ github.event.inputs.release_name }}"

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Connect to AKS Cluster
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az aks get-credentials \
            --resource-group "$RESOURCE_GROUP" \
            --name "$TARGET_CONTEXT" \
            --overwrite-existing
          kubectl config use-context "$TARGET_CONTEXT"
          kubectl config current-context

      - name: Run Database Backup Script
        run: |
          chmod +x ./hack/db-backup.sh
            ./hack/db-backup.sh

      - name: Upload Backup Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: db-backup-logs
          path: ./logs/**/*.log
          retention-days: 7

      - name: Upload Backup Files
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: db-backup-files
          path: ./backup/**/*.sql
          retention-days: 7
